apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-deployment
  labels:
    app: restaurante-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-api
  template:
    metadata:
      labels:
        app: restaurante-api
    spec:
      containers:
        - name: restaurante-api
          image: 550043459677.dkr.ecr.us-east-1.amazonaws.com/restauranteservice:1.5
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__RestauranteConnection
              value: "server=alura-db.cq8nnyklopj5.us-east-1.rds.amazonaws.com;database=restaurantedb;user=admin_alura;password=UiaUubJg7ytCBK1jAhwg"
            - name: RabbitMqHost
              value: "rabbitmq-service"
            - name: RabbitMqPort
              value: "5672"